version: '3.7'
services:
  app:
    container_name: project2-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - mailpit
    ports:
      - "8080:80"
    volumes:
      - ./laravel-project:/var/www/html
  mysql:
    image: mysql:8.1
    container_name: project2-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - project2-db:/var/lib/mysql/

  # redis service
  redis:
    image: redis:alpine
    container_name: project2-redis
    ports:
      - "6379:6379"
    volumes:
      - project2-redis:/data

  # mailpit - mail service
  mailpit:
    image: axllent/mailpit
    container_name: project2-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  laravel-exa:
    driver: bridge

volumes:
  project2-db:
    driver: local
  project2-redis:
    driver: local